title: Life record of our pets Cuba & Fiyi.
author: Fernando Saucedo
email: saucedo.info@gmail.com
description: >-
  Cameras: Fujifilm x70, nikon d610, motorola cell phones.

social:
  twitter: saucedoinfo
  instagram: saucedo.info
  github: saucedoinfo

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
